### ISSUE TITLE
[Epic] React Native PN Decryption as BackgroundService

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/notify-client-js#7]
## Context

- Both the Kotlin and Swift Push SDKs rely on an auxiliary background service to decrypt incoming PNs from APNS/FCM in the background on their respective platforms, before serving the decrypted notification payload to the user as a standard push notification.
	- [Swift implementation](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/main/Example/PNDecryptionService/NotificationService.swift)
	- [Kotlin implementation](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/develop/push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/PushMessageService.kt)
- We need to leverage a similar approach for React Native in order to allow a RN wallet using the JS Push SDK to achieve the same e2e notification receipt + decryption flow on iOS/Android via APNS/FCM.

## Approach 1

- Ideally we are able to simply **reuse the existing implementations of these services** as they have been already set up by the Swift/Kotlin teams **and write React Native bindings where necessary to aid interfacing with them**.
- The requirements for this to work seem to be:
	- Exposing the Swift/Kotlin service in such a way that a RN developer can install it
	- Swift/iOS:
		- Being able to instantiate `PushDecryptionService` and subsequently call `service.decryptMessage(topic: topic, ciphertext: ciphertext)` successfully (see [this line](https://github.com/WalletConnect/WalletConnectSwiftV2/blob/main/Example/PNDecryptionService/NotificationService.swift#L19))
	- Kotlin/Android:
		- Being able to call Kotlin `Push` SDK specific formatting (e.g. `Push.Wallet.Params.DecryptMessage`) and `PushWalletClient.decryptMessage(...)` (see [this line](https://github.com/WalletConnect/WalletConnectKotlinV2/blob/develop/push/sdk/src/main/kotlin/com/walletconnect/push/wallet/client/PushMessageService.kt#L33))
	- Adjust the JS Push SDK to have optional flows to use e.g. https://github.com/oblador/react-native-keychain in RN contexts, in order to write the keys needed for the service's decryption into the iOS keychain and/or Android Keystore
	- Build any additional RN native bindings/modules that we need to interface with the Swift/Kotlin background services: https://reactnative.dev/docs/native-modules-intro

### Possible issues
- This will require RN devs to not just implement the JS Push SDK, but also depend on the Swift and/or Kotlin SDKs under the hood to allow for background decryption of PNs.
- As Talha outlined below, this requires initialisation of the Kotlin client (likely similar in Swift), simply to get the `decryptMessage()` call off the ground.

## Approach 2

- Implement Swift/Kotlin background services specifically for RN, that:
	- do not directly depend on the Swift/Kotlin SDKs
	- are able to call back to the JS SDK's `decryptMessage` method via e.g. `RCTBridge`, hence avoiding the issue around native level decryption/keychain management.

See:
* RN + Android: https://reactnative.dev/docs/native-modules-android?android-language=kotlin#sending-events-to-javascript
* RN + iOS: https://reactnative.dev/docs/native-modules-ios#sending-events-to-javascript

### Possible issues

- Can we guarantee that the JS SDK will always receive the event and process it accordingly?

## Approach 3

- Implement "standalone" Swift/Kotlin background services specifically for RN, that:
	- do not directly depend on the Swift/Kotlin SDKs
	- are still able to perform the `decryptMessage` work, e.g. via a separate implementation of the `ChaCha20Poly` decryption logic and access to the required keys via the iOS keychain/Android Keystore, with values there previously populated by the JS SDK via e.g. https://github.com/oblador/react-native-keychain, https://github.com/pradeep1991singh/react-native-secure-key-store or interacting directly with the native keychain APIs from RN
	- This could be expedited if the Kotlin/Swift teams are able to provide the `decryptMessage` functionality packaged independently of their respective SDKs.

## Alternatives Considered

- @crypblizz8 and I investigated RN-first/JS-only approaches to the background service (e.g. https://github.com/Rapsssito/react-native-background-actions, https://github.com/transistorsoft/react-native-background-fetch), but none of these yielded something that would be reliable enough in production to ensure that the service is always available and the PN is always decrypted.

## Additional Resources

- https://medium.com/whitespectre/building-native-modules-for-react-native-with-kotlin-and-swift-f8103021c867
- https://medium.com/@pasinduyeshann/native-module-for-react-native-using-kotlin-1f169372b6d3

**Comment by bkrem** [comment]
@TalhaAli00 @llbartekll could you two take a look at the Approach section please and give input on feasibility in your eyes? 🙏 

I'm obviously not well versed on the details of how these services work in iOS/Android so would be grateful for an assessment of whether we can realistically reuse your services in some form, or need something more tailored for RN + JS Push

**Comment by llbartekll** [comment]
In swift the most important is to tore the subscription topic in group keychain so the service can decrypt it.
